wip: readme
teamgantt/subscreeb pull request #5
Opened 2020-09-02 00:05 UTC by tysonnero

2020-09-03 14:36 UTC, tysonnero commented
@johncorrelli This is ready for code review I would say

2020-09-03 14:50 UTC, tysonnero commented
@jcalebj Assigning you as well b/c I know you are good with the grammar and the English language.

2020-09-08 12:18 UTC, johncorrelli requested changes
Looking groovy - just a few things. :heart:

2020-09-08 12:18 UTC, johncorrelli commented on README.md
> +  - emailAddress - optional when creating a new customer
I know this is just a doc thing- but we should change this to required for new customers, since braintree needs to send emails.

2020-09-08 12:18 UTC, johncorrelli commented on README.md
> +- addOns (array)
We probably wanna say the `addOns` attr is optional.

2020-09-08 12:18 UTC, johncorrelli commented on README.md
> +- discounts (array)
We probably wanna say the `discounts` attr is optional.

2020-09-08 12:18 UTC, johncorrelli commented on README.md
> +    'discounts' => [
These look like they are arrays of arrays below... which sounds right, since it allows multiple addons/discounts. We should update to:

```php

'addons' => [
   [
        ....
   ]
],
'discounts' => [
   [
        ....
   ]
],
```

2020-09-08 12:18 UTC, johncorrelli commented on README.md
> +You can only update to a plan with the same billing cycle; at this time we do not allow you to update from a yearly plan to a monthly plan and vice versa.
We should add that this is a limitation of the braintree api, and suggested method is to cancel the existing subscription and creating a new one, and that the balance can be carried over into a discount.

2020-09-08 12:18 UTC, johncorrelli commented on README.md
> +status | The subscription's current status. | 'active', 'pending', 'cancelled' |
There are a few other status to include: https://developers.braintreepayments.com/reference/response/subscription/php#status

2020-09-08 13:28 UTC, jcalebj approved these changes
Concise, yet sufficiently helpful 🙇

2020-09-14 13:07 UTC, johncorrelli commented on README.md
> +  - emailAddress - optional when creating a new customer
I stand corrected - doesn't look like BT requires this according to [this](https://developers.braintreepayments.com/reference/request/customer/create/php)

2020-09-14 13:29 UTC, johncorrelli commented
@bradbumbalough since you were Tyson's pair during some of this, assigning this fixup to you. I just tacked it on as a last commit.

2020-09-14 17:26 UTC, bradbumbalough approved these changes

2020-09-28 12:24 UTC, merged